// Email konuları listesi
export const EMAIL_SUBJECTS = [
  { id: '1', title: 'Fatura Önizleme' },
  { id: '2', title: 'Sistem Yeni Kullanıcı Bilgilendirmesi' },
  { id: '3', title: 'Sistem Kullanıcı Şifre Hatırlatma' },
  { id: '4', title: 'Yeni Gelen Sipariş Bildirimi' },
  { id: '5', title: 'Ödeme Onayı Bekleyen Sipariş Bildirimi' },
  { id: '6', title: 'Kapıda Ödeme Onayı Beklenen Sipariş Bildirimi' },
  { id: '7', title: 'Kapıda Ödeme Onayı Alınan Sipariş Bildirimi' },
  { id: '8', title: 'Tedariki Başlatılan Sipariş Bildirimi' },
  { id: '9', title: 'Tedariki Sırasında Eksik Ürün Çıkan Sipariş Bildirimi' },
  { id: '10', title: 'Eksik Ürün Sebebi İle Aranan ve Ulaşılamayan Müşteriye Bildirim' },
  { id: '11', title: 'Kapıda Ödeme Sebebi İle Aranan ve Ulaşılamayan Müşteriye Bildirim' },
  { id: '12', title: 'Ödemesi Sonradan Onaylanan Siparişin Bildirimi' },
  { id: '13', title: 'İptal Siparişin Bildirimi' },
  { id: '14', title: 'İptal Sonucu Ödeme Çıkarılacağının Bildirimi' },
  { id: '15', title: 'Ödeme İçin IBAN Hesabı Bekleniyorsa IBAN Talep Bildirimi' },
  { id: '16', title: 'Ürünlerin Tedariki Tamamlandığında Bildirim' },
  { id: '17', title: 'Siparişin Faturası Kesildiğinde Bildirim' },
  { id: '18', title: 'Siparişin Son Kontrolü Tamamlandığında Bildirim' },
  { id: '19', title: 'Sipariş Kargoya Teslim Edildiğinde Bildirim' },
  { id: '20', title: 'Siparişin İadesi Geldiğinde Bildirim' },
  { id: '21', title: 'Siparişin İadesi Tamamlandığında ve Geri Ödemesi Kredi Kartına İade İse' },
  { id: '22', title: 'Eksik Ürün Alternatif Ürün Gönderimi' },
  { id: '23', title: 'İade İşlemi İçin Aranıp Ulaşamadığında Bildirim' },
  { id: '24', title: 'Siparişin İadesi Tamamlandığında ve Geri Ödemesi IBAN Hesabına İade İse' },
  { id: '25', title: 'Siparişin İadesi Tamamlandığında ve Geri Ödemesi Hediye Çeki Olarak Tanımlandıysa' },
  { id: '26', title: 'Siparişin İadesi Tamamlandığında ve Geri Ödemesi Bakiyesine Yüklendiyse' },
  { id: '27', title: 'Bekleyen Ödemenin Tamamlanması Anında' },
  { id: '28', title: 'Eksik Ürün Sebebi ile Aranan ve Ulaşılamadığından İptal Edilen Sipariş Bildirimi' },
  { id: '29', title: 'Siparişte Bakiye Kullanıldığında Gönder' },
  { id: '30', title: 'Şifremi Unuttum' },
  { id: '31', title: 'Kapıda Ödeme SMS Onayı' },
  { id: '32', title: 'Üyeliksiz Alışveriş Bildirimi' },
  { id: '33', title: 'İletişim Formuna Cevap Verildiğinde' },
  { id: '34', title: 'Yeni Gelen Sipariş Bildirimi, Kapıda Ödeme - Nakit' },
  { id: '35', title: 'Yeni Gelen Sipariş Bildirimi, Kapıda Ödeme - Pos' },
  { id: '36', title: 'Yeni Gelen Sipariş Bildirimi, Kredi Kartı' },
  { id: '37', title: 'Yeni Gelen Sipariş Bildirimi, Havale' },
  { id: '38', title: 'Yeni Gelen Sipariş Bildirimi, Ücretsiz Teslimat' },
  { id: '39', title: 'Müşteri Tarafından Oluşturulan İade Talep Bildirimi' },
  { id: '40', title: 'Müşteri Tarafından Oluşturulan İade Talep İptali Bildirimi' },
  { id: '41', title: 'Personel Tarafından Müşteri İade Talep İptali' },
  { id: '42', title: 'Açılmadan Gelen İade Teslim Alındığında' },
  { id: '43', title: 'Müşteriden Gelen İade Teslim Alındığında' },
]
